version: "3"

services:
  client:
    stdin_open: true
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - "/app/node_modules"
      - "./:/app"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.website.rule=Host(`staging.woolgens.net`)" # Change this from staging.woolgens.net to woolgens.net once we go online!
      - "traefik.http.routers.website.tls=true"
      - "traefik.http.services.website.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik"
    networks:
      - traefik

networks:
  traefik:
    external: true
